# id: 1
server:
  address: "server:12345"
loop:
  lapse: "0m20s"
  period: "5s"
log:
  level: "info"
closingMessage: "hello there"
closingBatch: "general kenobi"
amountOfBatch: 5
personInfo:
  name: "pedro"
  document: 418
  number: 303456
  surname: "pepito"
  bornDate: "1997-11-11"
